version: '3.1'

services:
  nightfoxcontainer:
    image: nightfox:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - postgresdb
    networks:
      - nightfoxnetwork
  postgresdb:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=capgemini
    networks:
      - nightfoxnetwork
  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
    networks:
      - nightfoxnetwork
volumes:
    postgres-data:
networks:
    nightfoxnetwork:
      driver: bridge




